[package]
name = "fluentai-effects"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"
anyhow.workspace = true
thiserror.workspace = true
dashmap = "5.5"
rand = "0.8"
chrono = "0.4"
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.11", features = ["v4"] }
serde_json = "1.0"
parking_lot = "0.12"
rustc-hash.workspace = true
axum = { version = "0.7", features = ["ws"] }
tower = "0.5"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing.workspace = true
url = "2.5"
futures = "0.3"
async-stream = "0.3"
tokio-tungstenite = "0.24"
futures-util = "0.3"
base64 = "0.22"
hyper = "1.0"

# Optional dependencies
fluentai-di = { path = "../fluentai-di", optional = true }

[dev-dependencies]
fluentai-parser = { path = "../fluentai-parser" }
fluentai-optimizer = { path = "../fluentai-optimizer" }
wiremock = "0.6"

[features]
default = []
di = ["fluentai-di"]

[[example]]
name = "custom_handlers"
path = "examples/custom_handlers.rs"

[[example]]
name = "di_integration"
path = "examples/di_integration.rs"
required-features = ["di"]
