[package]
name = "fluentai-doc-macros"
version = "0.1.0"
edition = "2021"
authors = ["FluentAI Contributors"]
description = "Documentation enforcement macros for FluentAI"
license = "MIT"
repository = "https://github.com/fluentai/fluentai"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
fluentai-stdlib = { path = "../fluentai-stdlib" }