//! Tests for JIT arithmetic operations

use fluentai_jit::JitCompiler;
use fluentai_parser::parse_flc;
use fluentai_vm::Compiler;
use fluentai_core::value::Value;

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_multiplication() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("3 * 4", 12),
        ("-5 * 7", -35),
        ("0 * 100", 0),
        ("(2 * 3) * (4 * 5)", 120),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Integer(n) => assert_eq!(n, expected, "Failed for: {}", source),
            _ => panic!("Expected integer result for: {}", source),
        }
    }
}

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_division() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("12 / 3", 4),
        ("100 / 5", 20),
        ("7 / 2", 3), // Integer division
        ("(100 / 5) / 4", 5),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Integer(n) => assert_eq!(n, expected, "Failed for: {}", source),
            _ => panic!("Expected integer result for: {}", source),
        }
    }
}

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_modulo() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("10 % 3", 1),
        ("20 % 7", 6),
        ("15 % 5", 0),
        ("(100 % 11) % 3", 1),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Integer(n) => assert_eq!(n, expected, "Failed for: {}", source),
            _ => panic!("Expected integer result for: {}", source),
        }
    }
}

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_comparison_operations() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("5 < 10", true),
        ("10 < 5", false),
        ("5 <= 5", true),
        ("6 <= 5", false),
        ("10 > 5", true),
        ("5 > 10", false),
        ("5 >= 5", true),
        ("4 >= 5", false),
        ("5 == 5", true),
        ("5 == 6", false),
        ("5 != 6", true),
        ("5 != 5", false),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Boolean(b) => assert_eq!(b, expected, "Failed for: {}", source),
            _ => panic!("Expected boolean result for: {}", source),
        }
    }
}

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_boolean_operations() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("true && true", true),
        ("true && false", false),
        ("false && true", false),
        ("false && false", false),
        ("true || true", true),
        ("true || false", true),
        ("false || true", true),
        ("false || false", false),
        ("!true", false),
        ("!false", true),
        ("!(true && false)", true),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Boolean(b) => assert_eq!(b, expected, "Failed for: {}", source),
            _ => panic!("Expected boolean result for: {}", source),
        }
    }
}

#[test]
#[ignore = "JIT compiler requires updates to work with FLC-generated bytecode format"]
fn test_complex_arithmetic() {
    let mut jit = JitCompiler::new().unwrap();
    let test_cases = vec![
        ("2 + 3 * 4", 14),
        ("(2 + 3) * 4", 20),
        ("100 - 50 / 2", 75),
        ("(100 - 50) / 2", 25),
        ("10 + 20 * 30 - 40", 570),
        ("((10 + 20) * 30) - 40", 860),
    ];

    for (source, expected) in test_cases {
        let ast = parse_flc(source).unwrap();
        let compiler = Compiler::new();
        let bytecode = compiler.compile(&ast).unwrap();

        let result = jit.compile_and_run(&bytecode).unwrap();
        match result {
            Value::Integer(n) => assert_eq!(n, expected, "Failed for: {}", source),
            _ => panic!("Expected integer result for: {}", source),
        }
    }
}