[package]
name = "fluentai-jit"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-bytecode = { path = "../fluentai-bytecode" }
fluentai-parser = { path = "../fluentai-parser" }
cranelift = "0.104"
cranelift-codegen = "0.104"
cranelift-module = "0.104"
cranelift-jit = "0.104"
cranelift-native = "0.104"
anyhow.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
fluentai-vm = { path = "../fluentai-vm" }
criterion.workspace = true

[[bench]]
name = "jit_benchmarks"
harness = false