[package]
name = "fluentai-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-effects = { path = "../fluentai-effects", optional = true }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
rustc-hash.workspace = true

[features]
default = ["effects"]
effects = ["fluentai-effects"]

[dev-dependencies]
fluentai-parser = { path = "../fluentai-parser" }
