[package]
name = "fluentai-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Minimal WASM bindings for FluentAI"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
fluentai-parser = { path = "../fluentai-parser" }
fluentai-core = { path = "../fluentai-core" }
console_error_panic_hook = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console"] }
js-sys = "0.3"