[package]
name = "fluentai-vm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
jit = ["fluentai-jit"]
renderer = ["fluentai-renderer"]

[dependencies]
fluentai-core = { path = "../fluentai-core" }
fluentai-bytecode = { path = "../fluentai-bytecode" }
fluentai-effects = { path = "../fluentai-effects" }
fluentai-stdlib = { path = "../fluentai-stdlib" }
fluentai-modules = { path = "../fluentai-modules" }
fluentai-di = { path = "../fluentai-di" }
fluentai-optimizer = { path = "../fluentai-optimizer" }
fluentai-jit = { path = "../fluentai-jit", optional = true }
fluentai-parser = { path = "../fluentai-parser" }
fluentai-renderer = { path = "../fluentai-renderer", optional = true }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
byteorder.workspace = true
rustc-hash.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
parking_lot.workspace = true
crossbeam-epoch = "0.9"
crossbeam-utils = "0.8"
crossbeam-queue = "0.3"
futures = "0.3"

[dev-dependencies]
criterion.workspace = true
fluentai-parser = { path = "../fluentai-parser" }
tempfile = "3.8"











































